apiVersion: v1
kind: ServiceAccount
metadata:
  name: ip-pass
  namespace: ip-pass
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-middleware-editor
rules:
- apiGroups: ["traefik.io"]
  resources: ["middlewares"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-middleware-editor-binding
subjects:
- kind: ServiceAccount
  name: ip-pass
  namespace: ip-pass
roleRef:
  kind: ClusterRole
  name: traefik-middleware-editor
  apiGroup: rbac.authorization.k8s.io
